# Generated by Django 5.2.6 on 2025-10-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppEstudiante', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_Carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_semestre', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='estudiantes', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='estudiantes_perms', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_Nivel', models.AutoField(primary_key=True, serialize=False)),
                ('numero_nivel', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_Materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('horas_semana', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_Nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id_Paralelo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_paralelo', models.IntegerField()),
                ('cupo_maximo', models.IntegerField()),
                ('aula', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_Inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('calificacion', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('id_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.carrera')),
                ('id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.estudiante')),
                ('id_Paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstudiante.paralelo')),
            ],
        ),
    ]
