# Generated by Django 5.2.6 on 2025-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstudiante', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_Estudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
